# Generated by Django 5.2.6 on 2025-10-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucandidate',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
