# Generated by Django 5.2.7 on 2025-11-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_exploration_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergalleryimage',
            name='local_uri',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
