# Generated by Django 5.2.7 on 2025-11-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usergalleryimage_local_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergalleryimage',
            name='label_alternatives',
            field=models.JSONField(blank=True, default=list, help_text="List of dicts: [{'name': '치킨', 'confidence': 0.95}, ...]"),
        ),
        migrations.AddField(
            model_name='usergalleryimage',
            name='label_confidence',
            field=models.FloatField(default=0.0, help_text='0.0-1.0 confidence'),
        ),
        migrations.AddField(
            model_name='usergalleryimage',
            name='label_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usergalleryimage',
            name='label_manually_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usergalleryimage',
            name='original_ai_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='usergalleryimage',
            index=models.Index(fields=['user', 'category_tag'], name='users_userg_user_id_39fdc0_idx'),
        ),
    ]
