# Generated by Django 5.2.7 on 2025-11-17 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usergalleryimage_label_alternatives_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='rl_weight_vector',
            field=models.JSONField(blank=True, default=list, help_text='RL-optimized weights for [text_sim, popularity, distance, price, freshness, query_sim, taste_align]'),
        ),
        migrations.CreateModel(
            name='RLWeightHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weights', models.JSONField(help_text='Weight vector [w1, w2, w3, w4, w5, w6, w7] for scoring function')),
                ('update_cycle', models.IntegerField(help_text='Cycle number (0, 1, 2, ...)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_method', models.CharField(choices=[('linucb', 'LinUCB'), ('thompson', 'Thompson Sampling'), ('policy_gradient', 'Policy Gradient')], default='linucb', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rl_weight_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='users_rlwei_user_id_a79f6b_idx'), models.Index(fields=['user', 'update_cycle'], name='users_rlwei_user_id_e472ae_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_id', models.IntegerField(blank=True, help_text='Menu ID from recommendation system', null=True)),
                ('restaurant_id', models.IntegerField(blank=True, help_text='Restaurant ID from recommendation system', null=True)),
                ('interaction_type', models.CharField(choices=[('scrap', 'User saved/scrapped a restaurant'), ('click', 'User clicked/opened a menu item'), ('view', 'User viewed a menu item'), ('hide', 'User swiped to hide a recommendation'), ('expand', 'User expanded/opened detail page'), ('allergic_reaction', 'User reported negative reaction')], max_length=20)),
                ('reward_value', models.FloatField(help_text='Reward signal: +1.0 scrap, +0.5 click, -1.0 hide, etc.')),
                ('context_query', models.TextField(blank=True, help_text='Natural language query that led to this interaction')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'timestamp'], name='users_useri_user_id_b44936_idx'), models.Index(fields=['user', 'interaction_type'], name='users_useri_user_id_b1dcc9_idx'), models.Index(fields=['timestamp'], name='users_useri_timesta_390cf1_idx')],
            },
        ),
    ]
