[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.7",
    "django-rest>=0.8.7",
    "django-rest-auth>=0.9.5",
    "djangorestframework>=3.16.1",
]
