# Generated by Django 5.2.7 on 2025-11-17 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menucandidate_image_url'),
        ('recommendation', '0001_initial'),
        ('restaurant', '0002_alter_restaurant_image_url_alter_restaurant_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuReasonFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semantic_similarity', models.FloatField(default=0.0, help_text='Text similarity score')),
                ('image_similarity', models.FloatField(default=0.0, help_text='Image/visual similarity score')),
                ('category_match_score', models.FloatField(default=0.0, help_text='Category preference match')),
                ('taste_alignment', models.FloatField(default=0.0, help_text='User taste preference alignment')),
                ('query_alignment', models.FloatField(default=0.0, help_text="Alignment with user's natural language query")),
                ('temporal_fit_score', models.FloatField(default=0.0, help_text='Time-based fit (breakfast/lunch/dinner)')),
                ('distance_score', models.FloatField(default=0.0, help_text='Distance appropriateness')),
                ('popularity_score', models.FloatField(default=0.0, help_text='Restaurant popularity/rating')),
                ('allergy_penalty', models.FloatField(default=0.0, help_text='Allergy conflict penalty')),
                ('dislike_penalty', models.FloatField(default=0.0, help_text='Disliked ingredient penalty')),
                ('explanation', models.TextField(blank=True, help_text='GPT-generated Korean explanation')),
                ('explanation_reason_keys', models.JSONField(blank=True, default=list, help_text='Top 3 reason keys that contributed most to recommendation')),
                ('final_score', models.FloatField(default=0.0, help_text='Final recommendation score')),
                ('query_context', models.TextField(blank=True, help_text="User's natural language query context")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reason_features', to='menu.menu')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_reason_features', to='restaurant.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_reason_features', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='recommendat_user_id_1bce42_idx'), models.Index(fields=['menu', 'user'], name='recommendat_menu_id_1fc12a_idx'), models.Index(fields=['restaurant', 'user'], name='recommendat_restaur_f5875a_idx')],
            },
        ),
    ]
