# Generated by Django 5.2.7 on 2025-11-17 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menucandidate_image_url'),
        ('recommendation', '0002_menureasonfeatures'),
        ('restaurant', '0002_alter_restaurant_image_url_alter_restaurant_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuExternalMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_uuid', models.CharField(db_index=True, help_text='External database menu UUID', max_length=36, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_mapping', to='menu.menu')),
            ],
            options={
                'indexes': [models.Index(fields=['external_uuid'], name='recommendat_externa_8f6a5e_idx')],
            },
        ),
        migrations.CreateModel(
            name='RestaurantExternalMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_uuid', models.CharField(db_index=True, help_text='External database restaurant UUID', max_length=36, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_mapping', to='restaurant.restaurant')),
            ],
            options={
                'indexes': [models.Index(fields=['external_uuid'], name='recommendat_externa_5ca4e1_idx')],
            },
        ),
    ]
